name: "Deploy to NuGet"

on: ["push"]

env: 
  PROJECT_PATH: "DockerImageDiff/DockerImageDiff.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{github.workspace}}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'


jobs:
  Deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/Checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: '3.1.x'

    - name: 'Restore packages'
      run: dotnet restore ${{env.PROJECT_PATH}}

    - name: 'Build project'
      run: dotnet build ${{env.PROJECT_PATH}} --no-restore --configuration Release --output ${{env.PACKAGE_OUTPUT_DIRECTORY}}

    - name: 'Push package'
      run: dotnet nuget push ${{env.PACKAGE_OUTPUT_DIRECTORY}}\*.nupkg -k ${{ secrets.NUGET_KEY }} -s ${{env.NUGET_SOURCE_URL}}
